<?php

namespace my\php\frontend\controllers;

use yii\helpers\Inflector;

use Toolkit\Stdlib\Str\StrBuffer;

class ToolkitController extends \yii\web\Controller
{

    public $layout = 'main' ;

    public function actions()
    {
        return array_merge(
//            ['some-test'=>[]],
            parent::actions()); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $widget = \yii\widgets\Menu::widget([
            'options' => ['class' => 'sidebar-menu treeview'],
            'items' => [

                ['label' => 'String Buffer', 'url' => ['str-buffer']],
                // this is the actionStrBuffer ‘s route
                ['label' => 'String Buffer', 'url' => [Inflector::camel2id('StrBuffer')]],
                ['label' => 'Submenu',
                    'url' => ['#'],
                    'template' => '<a href="{url}" >{label}<i class="fa fa-angle-left pull-right"></i></a>',
                    'items' => [
                        ['label' => 'Action', 'url' => '#'],
                        ['label' => 'Another action', 'url' => '#'],
                        ['label' => 'Something else here', 'url' => '#'],
                    ],
                ],
            ],
            'submenuTemplate' => "\n<ul class='treeview-menu'>\n{items}\n</ul>\n",
            'encodeLabels' => false, //allows you to use html in labels
            'activateParents' => true,]
        );

        return $this->renderContent($widget);
    }

    public function actionStrBuffer()
    {


        $buf = StrBuffer::new("c");
        $buf->prepend('ab');
        $buf->append('de');

        $str = (string)$buf; // "abcde"
        $str = $buf->toString(); // "abcde"
        // get and clean.
//        $str = $buf->fetch(); // "abcde"
        $str = $buf->join(','); // "ab,c,de"
        return $this->renderContent('result :>'.$str) ;

    }
}