<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace my\test\backend\controllers\base;

use my\test\common\models\UserDatum;
    use my\test\common\models\search\UserDatum as UserDatumSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* UserDatumController implements the CRUD actions for UserDatum model.
*/
class UserDatumController extends Controller
{
/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all UserDatum models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new UserDatumSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}

/**
* Displays a single UserDatum model.
* @param string $user_id
	 * @param string $attr
*
* @return mixed
*/
public function actionView($user_id, $attr)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($user_id, $attr),
]);
}

/**
* Creates a new UserDatum model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new UserDatum;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing UserDatum model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param string $user_id
	 * @param string $attr
* @return mixed
*/
public function actionUpdate($user_id, $attr)
{
$model = $this->findModel($user_id, $attr);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing UserDatum model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param string $user_id
	 * @param string $attr
* @return mixed
*/
public function actionDelete($user_id, $attr)
{
try {
$this->findModel($user_id, $attr)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$user_id, $attr',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the UserDatum model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param string $user_id
	 * @param string $attr
* @return UserDatum the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($user_id, $attr)
{
if (($model = UserDatum::findOne(['user_id' => $user_id, 'attr' => $attr])) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
