<?php

/**
 * This is the template for generating the migration class of a specified table.
 * DO NOT EDIT THIS FILE! It may be regenerated with Gii.
 */

use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var \year\gii\element_plus\generators\form\Generator $generator
 * @var string $tableName full table name
 */

// FIXME: 关于表单默认值的问题 可以通过字段类型取到其默认值：https://github.com/php-toolkit/stdlib/blob/master/src/Type.php#L94
// 也可以用ActiveRecord 取到默认值：https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#default-attribute-values

// TODO： 对TS 的支持
// todo: php 类型转换为typescript类型： spatie/typescript-transformer ｜https://typeschema.org/｜https://hybridly.dev/guide/typescript.html
// 万一用php库搞不定 还可以使用进程间通信 或者webdriver等手段通过无头浏览器让特定网站来完成转换

$genProp = function ($propName, $propType) {
  $propName = '$' . $propName;
  $propCode = <<<Code
  /**
   * @var $propType
   */
  public {$propName};
  Code;
  return  $propCode;
};

?>
<template>
  <!-- /** generate for table:  <?= $generator->tableName ?> | class: <?= $className ?> */ -->

  <el-table ref="multipleTableRef" :data="items" style="" @selection-change="handleSelectionChange"
                @sort-change="handleSortChange" :header-cell-class-name="handleHeadAddClass">
                <el-table-column type="selection" width="55" />
<?php 
    $propsCode = [] ;
    foreach ($properties as $property => $data) : ?>
      <?php
         // print_r($data, false);
        $propsCode[] = $genProp($data['name'],$data['type']);
        ?>
<el-table-column fixed prop="<?= $property ?>" label="<?= $labels[$property] ?>" width="120"  sortable='custom'/>
<?php endforeach; ?>

                <el-table-column fixed="right" label="Operations" width="120">
                    <template #default="{ row }">
                        <el-button link type="primary" size="small" @click="handleDetail(row)">Detail</el-button>
                        <el-button link type="primary" size="small" @click="handleEdit(row)">Edit</el-button>
                        <el-button link type="danger" size="small" @click="handleDelete(row.id)">delete</el-button>
                    </template>
                </el-table-column>
            </el-table>
</template>


<script setup>
import {reactive,ref} from 'vue'
  <?php
  //  \year\gii\common\utils\TsParser::run($classCode); 
   \yii\helpers\Json::$prettyPrint = true;
  ?>
</script>