<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace my\test\common\models\base;

use Yii;

/**
 * This is the base-model class for table "user_data".
 *
 * @property string $user_id
 * @property string $attr
 * @property string $val
 * @property string $aliasModel
 */
abstract class UserDatum extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_data';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'UserData');
        }else{
            return Yii::t('app', 'UserDatum');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'attr', 'val'], 'required'],
            [['user_id'], 'integer'],
            [['val'], 'string'],
            [['attr'], 'string', 'max' => 250],
            [['user_id', 'attr'], 'unique', 'targetAttribute' => ['user_id', 'attr'], 'message' => 'The combination of User ID and Attr has already been taken.']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_id' => Yii::t('app', 'User ID'),
            'attr' => Yii::t('app', 'Attr'),
            'val' => Yii::t('app', 'Val'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'user_id' => Yii::t('app', '用户主键id'),
            'attr' => Yii::t('app', '属性 用户键'),
            'val' => Yii::t('app', '对应的值 格式自己决定 推荐用json'),
            ]);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\UserDatumQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\UserDatumQuery(get_called_class());
    }


}
