<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace my\admin\common\models\base;

use Yii;

/**
 * This is the base-model class for table "ys_admin".
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $salt
 * @property string $last_ip
 * @property integer $last_time
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class Admin extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ys_admin';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'Admins');
        }else{
            return Yii::t('app', 'Admin');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['last_time', 'created_at'], 'integer'],
            [['name'], 'string', 'max' => 60],
            [['email', 'salt'], 'string', 'max' => 255],
            [['password', 'last_ip'], 'string', 'max' => 64],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
            'password' => 'Password',
            'salt' => 'Salt',
            'last_ip' => 'Last Ip',
            'last_time' => 'Last Time',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
            'password' => 'Password',
            'salt' => 'Salt',
            'last_ip' => 'Last Ip',
            'last_time' => 'Last Time',
            'created_at' => 'Created At',
            ]);
    }




}
