<?php
/**
 * This is the template for generating the model class of a specified table.
 * DO NOT EDIT THIS FILE! It may be regenerated with Gii.
 */

use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var schmunk42\giiant\generators\model\Generator $generator
 * @var string $tableName full table name
 * @var string $className class name
 * @var yii\db\TableSchema $tableSchema
 * @var string[] $labels list of attribute labels (name => label)
 * @var string[] $rules list of validation rules
 * @var string[] $searchModelRules list of validation rules for search Model
 * @var array $relations list of relations (name => relation declaration)
 *
 * @var $properties array list of properties (property => [type, name. comment])
 * @var $labels string[] list of attribute labels (name => label)
 * @var $rules string[] list of validation rules
 */
/**
 * type UserSearch struct {
 *      Id          int    `json:"id"` // int32
 *      Created     int    `json:"created"`
 *      Status      string `json:"status"`
 *      // 依赖Repo
 *      repo TodoRepo `json:"-" form:",omitempty"` // 注释啦
 * }
 */

?>
package domain

import (
"github.com/go-ozzo/ozzo-validation"
)

type <?= $className ?>Search struct {
    <?= $className ?>

}

// Validate validate  fields of the  search model <?= $className ?>Search.
func (m <?= $className ?>Search) Validate() error {
  <?php if (empty($searchModelRules)) : ?>
     return nil
  <?php else :?>
      return validation.ValidateStruct(&m,
            <?php echo  ( implode(",\n            ", $searchModelRules) . ",\n        ") ?>
      )
    <?php endif ?>
}
