<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace home\feedback\common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "feedback".
 *
 * @property integer $id
 * @property integer $cate_id
 * @property integer $type_id
 * @property string $username
 * @property string $id_card
 * @property string $tel
 * @property string $contact_address
 * @property string $subject
 * @property string $body
 * @property string $reply_department
 * @property integer $reply_at
 * @property string $reply_content
 * @property integer $admin_updated_by
 * @property integer $status
 * @property integer $hot_grade
 * @property string $user_ip
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Feedback extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'feedback';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cate_id', 'type_id', 'reply_at', 'admin_updated_by', 'status', 'hot_grade'], 'integer'],
            [['type_id', 'username', 'id_card', 'tel', 'contact_address', 'subject', 'body'], 'required'],
            [['body', 'reply_content'], 'string'],
            [['username', 'reply_department'], 'string', 'max' => 32],
            [['id_card', 'tel'], 'string', 'max' => 20],
            [['contact_address'], 'string', 'max' => 255],
            [['subject'], 'string', 'max' => 120],
            [['user_ip'], 'string', 'max' => 130]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cate_id' => 'Cate ID',
            'type_id' => 'Type ID',
            'username' => 'Username',
            'id_card' => 'Id Card',
            'tel' => 'Tel',
            'contact_address' => 'Contact Address',
            'subject' => 'Subject',
            'body' => 'Body',
            'reply_department' => 'Reply Department',
            'reply_at' => 'Reply At',
            'reply_content' => 'Reply Content',
            'admin_updated_by' => 'Admin Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status' => 'Status',
            'hot_grade' => 'Hot Grade',
            'user_ip' => 'User Ip',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'cate_id' => '类别',
            'type_id' => '类型',
            'username' => '反映人姓名',
            'id_card' => '身份证号',
            'tel' => '联系电话',
            'contact_address' => '联系地址',
            'subject' => '来信主题',
            'body' => '来信内容',
            'reply_department' => '答复部门',
            'reply_at' => '答复时间',
            'reply_content' => '答复结果',
            'admin_updated_by' => '管理员修改者id',
            'created_at' => '创建时间',
            'updated_at' => '最后修改时间',
            'status' => '状态',
            'hot_grade' => '是否热门',
            'user_ip' => '用户ip地址',
        ]);
    }




}
