<?php
/**
 * This is the template for generating the migration class of a specified table.
 * DO NOT EDIT THIS FILE! It may be regenerated with Gii.
 */

use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var \year\gii\form\generators\form\Generator $generator
 * @var string $tableName full table name
 */
?>


<h1><?= $generator->tableName ?></h1>

<form method="POST">
    <label>Email:</label><br />
    <input type="text" name="email"><br />
    <label>Message:</label><br />
    <textarea name="message"></textarea><br />

    <?php foreach ($properties as $property => $data): ?>
        <label><?= $labels[$property] ?>:</label><br />
        <input type="text" name="<?= $property?>"><br />

    <?php endforeach; ?>
    <input type="submit">

</form>
