<?php
/**
 * This is the template for generating the migration class of a specified table.
 * DO NOT EDIT THIS FILE! It may be regenerated with Gii.
 */

use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var \year\gii\form\generators\form\Generator $generator
 * @var string $tableName full table name
 * @var array $properties
 * @var array $labels the generated attribute labels (name => label)
 */
//var_dump($generator->generateLabelsFromComments);
//print_r($labels);
//print_r($properties);
?>


<h1><?= $generator->tableName ?></h1>


<table class="table">
    <thead>
    <tr>
        <?php foreach ($properties as $property => $data): ?>
            <th scope="col" > <?= $labels[$property] ?> </th>
        <?php endforeach; ?>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">1</th>
        <?php foreach ($properties as $property => $data): ?>
            <td>
                <?= $property ?>
            </td>
        <?php endforeach; ?>
    </tr>
    </tbody>
</table>