<?php
/**
 * This is the template for generating the model class of a specified table.
 * DO NOT EDIT THIS FILE! It may be regenerated with Gii.
*/
use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var schmunk42\giiant\generators\model\Generator $generator
 * @var string $tableName full table name
 * @var string $className class name
 * @var yii\db\TableSchema $tableSchema
 * @var string[] $labels list of attribute labels (name => label)
 * @var string[] $rules list of validation rules
 * @var array $relations list of relations (name => relation declaration)
 */

$modelServiceName = lcfirst($className).'Service' ;
$serviceFile = '../services/'.lcfirst($className) ;

// $apiPath = '/api_x/'. Inflector::camel2id(StringHelper::basename($generator->modelClass)) ;
$apiPath = '/api_x/'. $tableName ;

?>
import request from '../utils/request';
import { PAGE_SIZE } from '../constants';

export function fetch({ page }) {
    // return request(`<?= $apiPath ?>?_page=${page}&_limit=${PAGE_SIZE}`);
    return request(`<?= $apiPath ?>?page=${page}&per-page=${PAGE_SIZE}`); // 这里后端api的约定可能不一样 此处遵循yii的
}

export function view(id) {
    return request(`<?= $apiPath ?>/${id}`, {
        method: 'GET',
    });
}

export function remove(id) {
    return request(`<?= $apiPath ?>/${id}`, {
        method: 'DELETE',
    });
}

export function patch(id, values) {
    return request(`<?= $apiPath ?>/${id}`, {
        method: 'PATCH',
        body: JSON.stringify(values),
    });
}

export function create(values) {
    return request('<?= $apiPath ?>', {
        method: 'POST',
        body: JSON.stringify(values),
    });
}
