<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace my\content\common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "content_album".
 *
 * @property integer $id
 * @property integer $owner_id
 * @property string $name
 * @property string $desc
 * @property string $keywords
 * @property string $cover_uri
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $aliasModel
 */
abstract class Album extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'content_album';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['owner_id', 'status'], 'integer'],
            [['name'], 'required'],
            [['name', 'desc', 'keywords', 'cover_uri'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'owner_id' => '所有者的id',
            'name' => '相册名称',
            'desc' => '相册描述',
            'keywords' => '相册关键字',
            'cover_uri' => '封面图片',
            'status' => '状态',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'created_by' => '创建者id',
            'updated_by' => '更新者id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'owner_id' => '所有者的id',
            'name' => '相册名称',
            'desc' => '相册描述',
            'keywords' => '相册关键字',
            'cover_uri' => '封面图片',
            'status' => '状态',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'created_by' => '创建者id',
            'updated_by' => '更新者id',
        ]);
    }




}
