<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace my\content\common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "content_article_category".
 *
 * @property integer $id
 * @property integer $parent_id
 * @property string $name
 * @property integer $display_order
 * @property integer $mbr_count
 * @property integer $page_size
 * @property integer $status
 * @property string $redirect_url
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $aliasModel
 */
abstract class ArticleCategory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'content_article_category';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'display_order', 'mbr_count', 'page_size', 'status'], 'integer'],
            [['name'], 'required'],
            [['name', 'redirect_url'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => '上级分类',
            'name' => '名称',
            'display_order' => '显示顺序',
            'mbr_count' => '孩子数量',
            'page_size' => '每页显示数量',
            'status' => '状态 启用 关闭等',
            'redirect_url' => '跳转地址',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'created_by' => '创建者id',
            'updated_by' => '更新者id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'parent_id' => '上级分类',
            'name' => '名称',
            'display_order' => '显示顺序',
            'mbr_count' => '孩子数量',
            'page_size' => '每页显示数量',
            'status' => '状态 启用 关闭等',
            'redirect_url' => '跳转地址',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'created_by' => '创建者id',
            'updated_by' => '更新者id',
        ]);
    }




}
