<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace my\content\common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "content_article".
 *
 * @property integer $id
 * @property integer $cate_id
 * @property string $title
 * @property string $intro
 * @property string $content
 * @property string $rep_thumb
 * @property integer $display_order
 * @property integer $view_count
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $aliasModel
 */
abstract class Article extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'content_article';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cate_id', 'title', 'content'], 'required'],
            [['cate_id', 'display_order', 'view_count', 'status'], 'integer'],
            [['intro', 'content'], 'string'],
            [['title', 'rep_thumb'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cate_id' => '分类id',
            'title' => '标题',
            'intro' => '简单描述 tease',
            'content' => '内容',
            'rep_thumb' => '代表性小图片',
            'display_order' => '排序',
            'view_count' => '查看次数',
            'status' => '状态',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'created_by' => '创建者id',
            'updated_by' => '更新者id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'cate_id' => '分类id',
            'title' => '标题',
            'intro' => '简单描述 tease',
            'content' => '内容',
            'rep_thumb' => '代表性小图片',
            'display_order' => '排序',
            'view_count' => '查看次数',
            'status' => '状态',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'created_by' => '创建者id',
            'updated_by' => '更新者id',
        ]);
    }




}
