<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace my\content\common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "content_photo".
 *
 * @property integer $id
 * @property integer $owner_id
 * @property integer $album_id
 * @property string $title
 * @property string $desc
 * @property string $uri
 * @property string $ext
 * @property string $size
 * @property string $hash
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $aliasModel
 */
abstract class Photo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'content_photo';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['owner_id', 'album_id'], 'integer'],
            [['desc'], 'string'],
            [['uri'], 'required'],
            [['title', 'uri', 'ext', 'size'], 'string', 'max' => 255],
            [['hash'], 'string', 'max' => 32],
            [['hash'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'owner_id' => '所有者的id',
            'album_id' => '相册id',
            'title' => '图片标题',
            'desc' => '图片描述',
            'uri' => 'original uploaded image',
            'ext' => '图片扩展名',
            'size' => '图片大小',
            'hash' => '图片哈希',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'created_by' => '创建者id',
            'updated_by' => '更新者id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'owner_id' => '所有者的id',
            'album_id' => '相册id',
            'title' => '图片标题',
            'desc' => '图片描述',
            'uri' => 'original uploaded image',
            'ext' => '图片扩展名',
            'size' => '图片大小',
            'hash' => '图片哈希',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'created_by' => '创建者id',
            'updated_by' => '更新者id',
        ]);
    }




}
