<?php
/**
 * This is the template for generating the model class of a specified table.
 * DO NOT EDIT THIS FILE! It may be regenerated with Gii.
*/
use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var schmunk42\giiant\generators\model\Generator $generator
 * @var string $tableName full table name
 * @var string $className class name
 * @var yii\db\TableSchema $tableSchema
 * @var string[] $labels list of attribute labels (name => label)
 * @var string[] $rules list of validation rules
 * @var array $relations list of relations (name => relation declaration)
 */

$modelServiceName = lcfirst($className).'Service' ;
$serviceFile = '../services/'.lcfirst($className) ;
$routePath =   '/'. Inflector::camel2id(StringHelper::basename($className)) ;
$defaultApiPath = '/api_x/'.$tableName ;
?>
import * as <?= $modelServiceName ?> from '<?= $serviceFile ?>';

export default {
    namespace: '<?= $generator->ns ?>',
    state: {
        list: [],
        total: null,
        page: null,
    },
    reducers: {
        save(state, {payload}) {
            const {data : list , total, page} = payload ;
            return {...state, list, total, page};
        },
    },
    effects: {
        *fetch({payload: {page = 1}}, {call, put}) {
            const {data, headers} = yield call(<?= $modelServiceName ?>.fetch, {page});
            // TODO 此处可以查看异步请求的数据格式哦 然后根据格式解析payload  console.log(data) ;
            yield put({
                type: 'save',
                payload: {
                    data:data.data,
                    total: parseInt(headers['x-total-count'], 10), // 此header头 在util/request.js 中被填充了
                    page: parseInt(page, 10),
                },
            });
        },
        *remove({payload: id}, {call, put}) {
            yield call(<?= $modelServiceName ?>.remove, id);
            yield put({type: 'reload'});
        },
        *patch({payload: {id, values}}, {call, put}) {
            yield call(<?= $modelServiceName ?>.patch, id, values);
            yield put({type: 'reload'});
        },
        *create({payload: values}, {call, put}) {
            yield call(<?= $modelServiceName ?>.create, values);
            yield put({type: 'reload'});
        },
        *reload(action, {put, select}) {
            const page = yield select(state => state.<?= $generator->ns ?>.page);
            yield put({type: 'fetch', payload: {page}});
        },
    },
    subscriptions: {
        setup({dispatch, history}) {
            return history.listen(({pathname, query}) => {
                if (pathname === '<?= $routePath ?>') {
                    dispatch({type: 'fetch', payload: query});
                }
            });
        },
    },
};
